// generated by scripts/showcase-images.mjs from the master screenshots; do not edit.
// rerun `npm run images -- <masters-dir>` instead.
import type { ResponsiveImage } from "./responsive-image";

export const SHOWCASE_IMAGES = {
    // beadside-extra-dark-note-1920x1080-2x.png
    "beadside-note": {
        src: "/showcase/beadside-note-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/beadside-note-480.webp 480w, /showcase/beadside-note-800.webp 800w, /showcase/beadside-note-1200.webp 1200w, /showcase/beadside-note-1600.webp 1600w, /showcase/beadside-note-2000.webp 2000w, /showcase/beadside-note-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAgCdASoYAA4APu1iqU2ppaQiMAgBMB2JaQDKAC5JAAD+78dLta3L4+JUe51sgYAAAA==",
        color: "#22201d",
    },
    // beadside-waiting-1920x1080-2x.png
    beadside: {
        src: "/showcase/beadside-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/beadside-480.webp 480w, /showcase/beadside-800.webp 800w, /showcase/beadside-1200.webp 1200w, /showcase/beadside-1600.webp 1600w, /showcase/beadside-2000.webp 2000w, /showcase/beadside-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAwCdASoYAA4APu1iqk4ppaQiMAgBMB2JaQAAidpPhhAAAP7vuNnf3FopURdumWySaf0swAA=",
        color: "#f4f3f0",
    },
    // breakbeat-extra-editor-1920x1080-2x.png
    "breakbeat-editor": {
        src: "/showcase/breakbeat-editor-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/breakbeat-editor-480.webp 480w, /showcase/breakbeat-editor-800.webp 800w, /showcase/breakbeat-editor-1200.webp 1200w, /showcase/breakbeat-editor-1600.webp 1600w, /showcase/breakbeat-editor-2000.webp 2000w, /showcase/breakbeat-editor-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoYAA4APu1kqk2ppaQiMAgBMB2JZwC/OB5vMhBrDpjHgAAA/uBlBtHq04zLyFNirKo/Nq4U3qn7HeLZyIt81r0zQ2/3+5tl+XXFgAAA",
        color: "#988e9f",
    },
    // breakbeat-playground-1920x1080-2x.png
    breakbeat: {
        src: "/showcase/breakbeat-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/breakbeat-480.webp 480w, /showcase/breakbeat-800.webp 800w, /showcase/breakbeat-1200.webp 1200w, /showcase/breakbeat-1600.webp 1600w, /showcase/breakbeat-2000.webp 2000w, /showcase/breakbeat-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQBACdASoYAA4APu1mqk2ppaQiMAgBMB2JZwC7AB6XIY0/dKAD3JYgAAD+5z7AWCmz6K7o48aB3yM09gBo+MhG5FVrrFJTJrBxH8E+mIh0v2QoAAA=",
        color: "#9e94a3",
    },
    // diskzokej-dial-2560x1440.png
    diskzokej: {
        src: "/showcase/diskzokej-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/diskzokej-480.webp 480w, /showcase/diskzokej-800.webp 800w, /showcase/diskzokej-1200.webp 1200w, /showcase/diskzokej-1600.webp 1600w, /showcase/diskzokej-2000.webp 2000w, /showcase/diskzokej-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBYdhaD1YPoAAP7uflYQ/JJJHwm7DvztWx9nza/oxwubGEiAAA==",
        color: "#561048",
    },
    // fonts-swipe-2560x1440.png
    fonts: {
        src: "/showcase/fonts-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/fonts-480.webp 480w, /showcase/fonts-800.webp 800w, /showcase/fonts-1200.webp 1200w, /showcase/fonts-1600.webp 1600w, /showcase/fonts-2000.webp 2000w, /showcase/fonts-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAwCdASoYAA4APu1iqU2ppaQiMAgBMB2JZwDImC0HbhgAAP7wF9Z4m4vfnNwGIqa2r3HkzgAAAA==",
        color: "#f8f7f5",
    },
    // good-cookie-hero-1920x1080-2x.png
    "good-cookie": {
        src: "/showcase/good-cookie-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/good-cookie-480.webp 480w, /showcase/good-cookie-800.webp 800w, /showcase/good-cookie-1200.webp 1200w, /showcase/good-cookie-1600.webp 1600w, /showcase/good-cookie-2000.webp 2000w, /showcase/good-cookie-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCdACHS18cH7JRUj6AA/vAGSK9QODm7aFoBEQy3YdOasv8v9VjvGVbjFjsOlGZ+plllD1guVA7lo9Sa63oOmh3d6XwkvMHgAA==",
        color: "#cec4b8",
    },
    // models-extra-frontier-1920x1080-2x.png
    "models-frontier": {
        src: "/showcase/models-frontier-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/models-frontier-480.webp 480w, /showcase/models-frontier-800.webp 800w, /showcase/models-frontier-1200.webp 1200w, /showcase/models-frontier-1600.webp 1600w, /showcase/models-frontier-2000.webp 2000w, /showcase/models-frontier-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAgCdASoYAA4APu1iqU2ppaQiMAgBMB2JaQAAe/QAAP7wIj6nQYn5uzBeUUCXgAA=",
        color: "#161719",
    },
    // models-table-1920x1080-2x.png
    models: {
        src: "/showcase/models-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/models-480.webp 480w, /showcase/models-800.webp 800w, /showcase/models-1200.webp 1200w, /showcase/models-1600.webp 1600w, /showcase/models-2000.webp 2000w, /showcase/models-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAgCdASoYAA4APu1iqU2ppaOiMAgBMB2JaQAAe/QAAP7v/+AC65moyGHcZksiEAA=",
        color: "#171a1c",
    },
    // nakup-2-she-adds-390x844-3x.png
    "nakup-adds": {
        src: "/showcase/nakup-adds-1170.webp",
        width: 1170,
        height: 2532,
        srcSet: "/showcase/nakup-adds-480.webp 480w, /showcase/nakup-adds-800.webp 800w, /showcase/nakup-adds-1170.webp 1170w",
        placeholder: "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAACwBQCdASoYADQAPu1sqlCppiOiqAwBMB2JQBiDf4A1KHtCk0jyH35gXeSjsDU+mHzi2KOfjgAA/q6pxLijf/rlFkdZBMipxTX/IhCkvwa5o5Sec2ufDIeDug96qMw/j6ZI8G33CAhXfNpaUQrt8/q5FnKd0wfpOuy6Wvi5nt5QT8MOuVaNKssDfgWwFKhLpkkYgaikhCTk7XXqwfY/30VPBS+6RqbesSktYt1uBfW6UEqLenTIjlf8onTpHDAwAAA=",
        color: "#e7ebf0",
    },
    // nakup-1-list-390x844-3x.png
    "nakup-list": {
        src: "/showcase/nakup-list-1170.webp",
        width: 1170,
        height: 2532,
        srcSet: "/showcase/nakup-list-480.webp 480w, /showcase/nakup-list-800.webp 800w, /showcase/nakup-list-1170.webp 1170w",
        placeholder: "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAQBQCdASoYADQAPu1ko02ppaKjMBv8ATAdiWIAyNQQQvnNz5+oGWPIkSHRbmPBI+KAANaF2AEDc0i27JuK+BP5wgTUExb+3nNm7LH/3kf7R+s8o9FMMmSVL/YuSaCofb0zUAhkFsMolCLM08CTbg3IWQNzn8q7cY26UnKl/CGH3m3kIWcDZuM1yc6T2j/FiNIp/b/iPSw2z5StEuQWdUpIAAA=",
        color: "#efebe3",
    },
    // nakup-3-in-the-shop-390x844-3x.png
    "nakup-shop": {
        src: "/showcase/nakup-shop-1170.webp",
        width: 1170,
        height: 2532,
        srcSet: "/showcase/nakup-shop-480.webp 480w, /showcase/nakup-shop-800.webp 800w, /showcase/nakup-shop-1170.webp 1170w",
        placeholder: "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAADwBACdASoYADQAPu1wr1GppqQjqAlZMB2JYwDLaAtJ2uUerQ3hCqEgj8bZG9FYwsQA05/WGbrshPHcHQi2ttXvXEuDbnv7QMeXD3OH2DMHx5z6BmsrxXZb0ApaqMsjjyPTZFYljkipqvVWYNmxWKMCvGIolZZRDSjmKBYo3iMqyWAWFT4z1HTiO+Bm5Mxl1i5eUaPrG6IsayY1kBXkOXc0scyy5bCpK8ORekSc5QAAAA==",
        color: "#ede9de",
    },
    // t3-extra-ctrl-tab-1920x1080-2x.png
    "t3-switcher": {
        src: "/showcase/t3-switcher-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/t3-switcher-480.webp 480w, /showcase/t3-switcher-800.webp 800w, /showcase/t3-switcher-1200.webp 1200w, /showcase/t3-switcher-1600.webp 1600w, /showcase/t3-switcher-2000.webp 2000w, /showcase/t3-switcher-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAgCdASoYAA4APu1iqk2ppaQiMAgBMB2JZwC/OC0kAAD+8G+NikN4WIu5xH13m79OZDFaiij03QAA",
        color: "#0d0e18",
    },
    // t3-hero-1920x1080-2x.png
    t3: {
        src: "/showcase/t3-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/t3-480.webp 480w, /showcase/t3-800.webp 800w, /showcase/t3-1200.webp 1200w, /showcase/t3-1600.webp 1600w, /showcase/t3-2000.webp 2000w, /showcase/t3-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZQAAW/EJ0+CYAP7u3CX0SMyQs19+yQuwwIi3BYIivQkpRkMAAA==",
        color: "#111018",
    },
    // tally-extra-timeline-2560x1440.png
    "tally-timeline": {
        src: "/showcase/tally-timeline-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/tally-timeline-480.webp 480w, /showcase/tally-timeline-800.webp 800w, /showcase/tally-timeline-1200.webp 1200w, /showcase/tally-timeline-1600.webp 1600w, /showcase/tally-timeline-2000.webp 2000w, /showcase/tally-timeline-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwAAidpukI4AAP7wLnVye+muE2luV/Wu9q8id1jgAA==",
        color: "#f3f0ea",
    },
    // tally-today-2560x1440.png
    tally: {
        src: "/showcase/tally-2560.webp",
        width: 2560,
        height: 1440,
        srcSet: "/showcase/tally-480.webp 480w, /showcase/tally-800.webp 800w, /showcase/tally-1200.webp 1200w, /showcase/tally-1600.webp 1600w, /showcase/tally-2000.webp 2000w, /showcase/tally-2560.webp 2560w",
        placeholder: "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwAAetDz7r8AAP7wLuohohfbcMFLZZ3dxniUsV6AAA==",
        color: "#f3f0ea",
    },
} as const satisfies Record<string, ResponsiveImage>;

export type ShowcaseImageId = keyof typeof SHOWCASE_IMAGES;
