// generated by scripts/showcase-images.mjs from the master screenshots; do not edit.
// rerun `npm run images -- <masters-dir>` instead.
import type { ResponsiveImage } from "./responsive-image";

export const SHOWCASE_IMAGES = {
    // beadside.webp
    beadside: {
        src: "/showcase/beadside-1600.webp",
        width: 1600,
        height: 900,
        srcSet: "/showcase/beadside-480.webp 480w, /showcase/beadside-800.webp 800w, /showcase/beadside-1200.webp 1200w, /showcase/beadside-1600.webp 1600w",
        placeholder: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAwCdASoYAA4APu1iqU2ppaQiMAgBMB2JaQDE2C0HxcAAAP7vuKV/tFbJRHanXpAmNydgAAA=",
        color: "#f5f3ef",
    },
    // diskzokej.webp
    diskzokej: {
        src: "/showcase/diskzokej-1440.webp",
        width: 1440,
        height: 900,
        srcSet: "/showcase/diskzokej-480.webp 480w, /showcase/diskzokej-800.webp 800w, /showcase/diskzokej-1200.webp 1200w, /showcase/diskzokej-1440.webp 1440w",
        placeholder: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAgCdASoYAA8APu1iqU2ppaOiMAgBMB2JaQC7ADKtAAD+7zJh5lMDx8caLfKT2dFv0vn3dQsRXG+KAAA=",
        color: "#211e18",
    },
    // fonts.webp
    fonts: {
        src: "/showcase/fonts-1440.webp",
        width: 1440,
        height: 900,
        srcSet: "/showcase/fonts-480.webp 480w, /showcase/fonts-800.webp 800w, /showcase/fonts-1200.webp 1200w, /showcase/fonts-1440.webp 1440w",
        placeholder: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAwCdASoYAA8APu1iqU2ppaOiMAgBMB2JaQDImC0HbEgA/u+VUf7JVMSww5BMxCF+2p3hwwlggAAA",
        color: "#f1efee",
    },
    // good-cookie.webp
    "good-cookie": {
        src: "/showcase/good-cookie-1440.webp",
        width: 1440,
        height: 900,
        srcSet: "/showcase/good-cookie-480.webp 480w, /showcase/good-cookie-800.webp 800w, /showcase/good-cookie-1200.webp 1200w, /showcase/good-cookie-1440.webp 1440w",
        placeholder: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoYAA8APu1iqk2ppaQiMAgBMB2JYwCdACHZ16P3zYqWFcgA/vAD8CvO7Av8/N8ZwgqgTF4IkfEz8HiQ/+39peoAYyQi0NRirTTo3NZ84fT55cqJHBUwu+rgD9FjnHz1B6qyqexnaKp4AA==",
        color: "#bcb5aa",
    },
    // models.webp
    models: {
        src: "/showcase/models-1440.webp",
        width: 1440,
        height: 900,
        srcSet: "/showcase/models-480.webp 480w, /showcase/models-800.webp 800w, /showcase/models-1200.webp 1200w, /showcase/models-1440.webp 1440w",
        placeholder: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAgCdASoYAA8APu1iqk2ppaQiMAgBMB2JaQAAe/QAAP7v4Ivynv/enYPTd3dz9ue4YkMAAAA=",
        color: "#17191a",
    },
    // nakup.webp
    nakup: {
        src: "/showcase/nakup-440.webp",
        width: 440,
        height: 850,
        srcSet: "/showcase/nakup-440.webp 440w",
        placeholder: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQBACdASoYAC4APu1wsFKppiSnpWmZMB2JYwAAHzp/ObJmXwH/TDa8rv6gAP6ucePPwxIIOzTmWV/wa7d/ROUP/1VpaTXJC+cWEDFN32rPIki7OM4wBVaKqMxA1cEAEngAAA==",
        color: "#eeeee9",
    },
    // t3.webp
    t3: {
        src: "/showcase/t3-1440.webp",
        width: 1440,
        height: 900,
        srcSet: "/showcase/t3-480.webp 480w, /showcase/t3-800.webp 800w, /showcase/t3-1200.webp 1200w, /showcase/t3-1440.webp 1440w",
        placeholder: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAgCdASoYAA8APu1iqU2ppaQiMAgBMB2JYwAAfqoAAP7wPJzhGUJLHB77Kz5WCuClOr79wZ4t/gzonQAAAA==",
        color: "#151223",
    },
    // tally.webp
    tally: {
        src: "/showcase/tally-1440.webp",
        width: 1440,
        height: 900,
        srcSet: "/showcase/tally-480.webp 480w, /showcase/tally-800.webp 800w, /showcase/tally-1200.webp 1200w, /showcase/tally-1440.webp 1440w",
        placeholder: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAwCdASoYAA8APu1iqU2ppaQiMAgBMB2JaQDE2B4+lTAA/uf7fVyWTB+KKRxvxtLdt7Kix/nRkGY7AAA=",
        color: "#f1f0ea",
    },
} as const satisfies Record<string, ResponsiveImage>;

export type ShowcaseImageId = keyof typeof SHOWCASE_IMAGES;
